# -*- coding: utf-8 -*-
"""SHF_MVI_main_class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rae7dukYhzrdRKrbUtbA4hiQcprYTpkZ
"""

import argparse
import pandas as pd
import pickle
import numpy as np



def predict_top_k(model, data, top_k=5):
    # Predict probabilities and get top-k indices
    probs = model.predict_proba(data)
    top_indices = np.argsort(probs, axis=1)[:, ::-1][:, :top_k]
    return top_indices



def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=str, required=True)
    parser.add_argument("--model", type=str, required=True)
    parser.add_argument("--encoder", type=str, required=True)
    parser.add_argument("--scaler", type=str, required=True)
    parser.add_argument("--columns", type=str, required=True, help="Pickle file containing cat_cols and num_cols")
    parser.add_argument("--top", type=int, default=5)
    args = parser.parse_args()

    # Load input data
    data = pd.read_csv(args.input)

    # Drop the target column if present
    target_column = "Technique Name"
    if target_column in data.columns:
        data = data.drop(columns=[target_column])

    # Load model, encoder, scaler, and column info
    with open(args.model, "rb") as f:
        model = pickle.load(f)
    with open(args.encoder, "rb") as f:
        encoder = pickle.load(f)
    with open(args.scaler, "rb") as f:
        scaler = pickle.load(f)
    with open(args.columns, "rb") as f:
        columns_info = pickle.load(f)

    cat_cols = columns_info["cat_cols"]
    num_cols = columns_info["num_cols"]

    # Encode categorical columns
    if len(cat_cols) > 0:
        data[cat_cols] = encoder.transform(data[cat_cols])

    # Scale numeric columns
    if len(num_cols) > 0:
        data[num_cols] = scaler.transform(data[num_cols])


   # Predict top-k
    top_preds = predict_top_k(model, data, top_k=args.top)

    # Convert indices to labels
    if hasattr(model, "classes_"):
        top_labels = model.classes_[top_preds]
    else:
        top_labels = top_preds



    # Print nicely formatted output per sample
    for i, labels in enumerate(top_labels):
        print(f"\nTop-k recommendations for sample #{i+1}:")
        for rank, label in enumerate(labels, start=1):
            print(f"{rank}- {label}")


if __name__ == "__main__":
    main()